<?php
return array(
    'bot_token' => 'YOUR_BOT_TOKEN',
    'bot_username' => 'YOUR_BOT_USERNAME',
    'admin_ids' => array(123456789),
    'base_url' => 'https://your-domain.com/public',
    'timezone' => 'UTC',
    'security' => array(
        'webhook_secret' => 'CHANGE_THIS_TO_A_LONG_RANDOM_SECRET',
        'validate_webhook_secret' => false,
        'secret_header_name' => 'X-Telegram-Bot-Api-Secret-Token',
        'max_text_length' => 4000,
        'max_caption_length' => 900,
        'request_size_limit' => 1048576,
        'strict_private_chat_only' => true,
        'username_pattern' => '/^[A-Za-z0-9_]{3,64}$/',
        'payment_amount_min' => 10,
        'payment_amount_max' => 1000000,
        'state_ttl' => 3600,
        'callback_ttl' => 300,
        'admin_reply_prefix' => '/reply_',
        'log_errors' => true,
    ),
    'storage' => array(
        'data_dir' => __DIR__ . '/data/json',
        'lang_dir' => __DIR__ . '/data/lang',
        'log_dir'  => __DIR__ . '/storage/logs',
        'cache_dir'=> __DIR__ . '/storage/cache',
        'lock_dir' => __DIR__ . '/storage/locks',
        'file_permissions' => 0640,
        'dir_permissions' => 0750,
    ),
    'bot' => array(
        'currency' => 'USD',
        'default_language' => 'en',
        'support_username' => '@your_support',
        'help_channel_url' => '',
        'maintenance_mode' => false,
        'maintenance_text_en' => 'Bot is under maintenance. Please try again later.',
        'maintenance_text_fa' => 'ربات در حال بروزرسانی است. بعداً دوباره تلاش کنید.',
        'require_join' => false,
        'required_channels' => array(),
    ),
    'rate_limits' => array(
        'global_user' => array('limit' => 30, 'window' => 60),
        'buy' => array('limit' => 8, 'window' => 60),
        'contact' => array('limit' => 6, 'window' => 600),
        'payment_submit' => array('limit' => 6, 'window' => 1800),
        'admin_actions' => array('limit' => 100, 'window' => 60),
    )
);
